### ISSUE TITLE
npm test script does not find LWdb.js

### ISSUE THREAD

**Issue by hhzl** [hhzl/LearnWords2#2]
I have added

	new file:   spec/learnwords2/LWdbSpec.js
	new file:   src/LWdb.js

The jasmine task started by ``npm test`` does not find ``LWdb.js``.

**Comment by phyiction** [comment]
You didn't include LWdb.js in the LWdbSpec.js. You'll need a require statement in LWdbSpec.js and and "export" the LWdb module. I've submitted a [pull request](https://github.com/hhzl/LearnWords2/pull/25) for this.
