### ISSUE TITLE
How do I set up a browser project which uses the component?

### ISSUE THREAD

**Issue by hhzl** [hhzl/LearnWords2#21]
Write developer notes about how to set up a project like #19 

Include 
* a general note about bower 
* instructions for loading the component with bower
* Step by step instructions how to a new project with the component

**Comment by phyiction** [comment]
To reduce the number of package management systems I would just stick with npm.

**Comment by hhzl** [comment]
To stick with `npm` is fine for me.

**Comment by hhzl** [comment]
The `demo.html` in `public` shows how to use the library.

The setup is generated by  calling `grunt` on the command line,
