### ISSUE TITLE
Plan for release 0.1 -- beta2 version released

### ISSUE THREAD

**Issue by hhzl** [hhzl/LearnWords2#23]
- Jasmine set up for browser and node command line.
- Constructor function for BoxOfQuestions() and some more specs.
- Have a build process for a release file for use in the browser.
- Documentation updated so that context information is given.

**Comment by hhzl** [comment]
Updated  version:

- Jasmine set up for browser and node command line. DONE
- Constructor function for BoxOfQuestions() and some more specs. (Singleton) NEED CHECKING
- Have a build process for a release file for use in the browser. (POSTPONE for release 0.2)
- Documentation updated so that context information is given.
- Check LWdb API about conformance with LWdb in https://github.com/hhzl/LearnWords or https://github.com/e1r0nd/LearnWords and if necessary make changes on either one or the other or on both sides.

**Comment by phyiction** [comment]
My understanding is that this is a standalone library. It would make sense to implement a "build process for a release file for use in the browser" in the application.

**Comment by hhzl** [comment]
That would be great, if we can include this in release 0.1. Earlier I thought of doing it in a later release.
