### ISSUE TITLE
Jasmine test in browser

### ISSUE THREAD

**Issue by hhzl** [hhzl/LearnWords2#6]
There is now a branch https://github.com/hhzl/LearnWords2/tree/JasmineInBrowser which has a file SpecRunner.html in the root directory so that Jasmin tests may be run in the browser.

Check the setup; compare with issue #2

**Comment by phyiction** [comment]
I've submitted a [pull request](https://github.com/hhzl/LearnWords2/pull/33) for this. To simplify I decided not to use watchify. Running npm test will generate build/jasmine-app-bundle.js which is included in specRunner.html. Now you can navigate to specRunner.html or the console to see the results.
